server:
  port: 8080

# Logging configuration
logging:
  level:
    # Set the root logger to INFO
    root: INFO
    # Set our application's package to DEBUG for more detailed logs during development
    com.example.musicparty: DEBUG

# Custom application properties
app:
  music-api:
    admin-password: ${ADMIN_PASSWORD:}
    netease:
      # The base URL of your deployed NeteaseCloudMusicApi instance
      base-url: ${NETEASE_API_URL:http://localhost:3000}
      cookie:
        ${NETEASE_COOKIE:}
    bilibili:
      # Bilibili API base URL, it's public
      base-url: "https://api.bilibili.com"
      sessdata: ${BILIBILI_SESSDATA:}
