server:
  port: 8080

# Logging configuration
logging:
  level:
    # Set the root logger to INFO
    root: INFO
    # Set our application's package to DEBUG for more detailed logs during development
    com.example.musicparty: DEBUG

# Custom application properties
app:
  music-api:
    admin-password: ganyh1998
    base-url: ${BASE_URL:http://localhost:8080}
    netease:
      # The base URL of your deployed NeteaseCloudMusicApi instance
      base-url: ${NETEASE_API_URL:http://localhost:3000}
      cookie:
        ${NETEASE_COOKIE:}
    bilibili:
      # Bilibili API base URL, it's public
      base-url: "https://api.bilibili.com"
      sessdata: ${BILIBILI_SESSDATA:}
    queue:
      max-size: ${QUEUE_MAX_SIZE:1000}
      history-size: ${QUEUE_HISTORY_SIZE:50}
    player:
      max-playlist-import-size: ${PLAYLIST_IMPORT_LIMIT:100}
    chat:
      max-history-size: ${CHAT_HISTORY_LIMIT:1000}
    cache:
      max-size: ${CACHE_MAX_SIZE:1GB}
